USE [master]
GO
/****** Object:  Database [RPGSystem]    Script Date: 6/18/2016 9:28:36 PM ******/
CREATE DATABASE [RPGSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RPGSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RPGSystem.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RPGSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\RPGSystem_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [RPGSystem] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RPGSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RPGSystem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RPGSystem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RPGSystem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RPGSystem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RPGSystem] SET ARITHABORT OFF 
GO
ALTER DATABASE [RPGSystem] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RPGSystem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RPGSystem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RPGSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RPGSystem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RPGSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RPGSystem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RPGSystem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RPGSystem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RPGSystem] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RPGSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RPGSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RPGSystem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RPGSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RPGSystem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RPGSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RPGSystem] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RPGSystem] SET RECOVERY FULL 
GO
ALTER DATABASE [RPGSystem] SET  MULTI_USER 
GO
ALTER DATABASE [RPGSystem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RPGSystem] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RPGSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RPGSystem] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [RPGSystem] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'RPGSystem', N'ON'
GO
USE [RPGSystem]
GO
/****** Object:  Table [dbo].[Atributo]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Atributo](
	[idAtributo] [int] IDENTITY(1,1) NOT NULL,
	[tipo] [char](1) NOT NULL,
	[nome] [varchar](50) NOT NULL,
	[descricao] [varchar](255) NULL,
 CONSTRAINT [PK_ATRIBUTO] PRIMARY KEY CLUSTERED 
(
	[idAtributo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Atributo_Historia]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Atributo_Historia](
	[idHistoria] [int] NOT NULL,
	[idAtributo] [int] NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Atributo_Personagem]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Atributo_Personagem](
	[idPersonagem] [int] NOT NULL,
	[idAtributo] [int] NOT NULL,
	[valorInt] [int] NULL,
	[valorStr] [varchar](255) NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Caminho]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Caminho](
	[idCaminho] [int] IDENTITY(1,1) NOT NULL,
	[idHistoriaOrigem] [int] NOT NULL,
	[idHistoriaDestino] [int] NOT NULL,
	[idCondicao] [int] NOT NULL,
 CONSTRAINT [PK_CAMINHO] PRIMARY KEY CLUSTERED 
(
	[idCaminho] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Capitulo]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Capitulo](
	[idCapitulo] [int] IDENTITY(1,1) NOT NULL,
	[Texto] [text] NOT NULL,
	[titulo] [varchar](255) NULL,
	[startChapter] [bit] NOT NULL,
	[idHistoria] [int] NOT NULL,
 CONSTRAINT [PK_CAPITULO] PRIMARY KEY CLUSTERED 
(
	[idCapitulo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Condicao]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Condicao](
	[idCondicao] [int] IDENTITY(1,1) NOT NULL,
	[idTipoCondicao] [int] NOT NULL,
 CONSTRAINT [PK_CONDICAO] PRIMARY KEY CLUSTERED 
(
	[idCondicao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Especie]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Especie](
	[idEspecie] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](50) NOT NULL,
	[descricao] [varchar](255) NULL,
 CONSTRAINT [PK_ESPECIE] PRIMARY KEY CLUSTERED 
(
	[idEspecie] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Historia]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Historia](
	[idHistoria] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](255) NOT NULL,
	[idCriador] [int] NOT NULL,
 CONSTRAINT [PK_HISTORIA] PRIMARY KEY CLUSTERED 
(
	[idHistoria] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Item]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Item](
	[idItem] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](1) NOT NULL,
	[attack] [int] NULL,
	[range] [bigint] NULL,
	[idEspecie] [int] NULL,
 CONSTRAINT [PK_ITEM] PRIMARY KEY CLUSTERED 
(
	[idItem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Item_Capitulo]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Item_Capitulo](
	[idCapitulo] [int] NOT NULL,
	[idItem] [int] NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Item_Personagem]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Item_Personagem](
	[idItem] [int] NOT NULL,
	[idPersonagem] [int] NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Login]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Login](
	[idLogin] [int] IDENTITY(1,1) NOT NULL,
	[login] [varchar](100) NOT NULL,
	[senha] [varchar](255) NOT NULL,
	[nivel] [char](1) NULL,
	[email] [varchar](50) NULL,
 CONSTRAINT [PK_LOGIN] PRIMARY KEY CLUSTERED 
(
	[idLogin] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Login_Personagem]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Login_Personagem](
	[idLoginPersonagem] [int] NOT NULL,
	[idLogin] [int] NOT NULL,
	[idPersonagem] [int] NOT NULL,
 CONSTRAINT [PK_LOGIN_PERSONAGEM] PRIMARY KEY CLUSTERED 
(
	[idLoginPersonagem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Personagem]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Personagem](
	[idPersonagem] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](100) NOT NULL,
	[imagem] [image] NULL,
 CONSTRAINT [PK_PERSONAGEM] PRIMARY KEY CLUSTERED 
(
	[idPersonagem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Saves]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Saves](
	[idPersonagem] [int] NOT NULL,
	[idHistoria] [int] NOT NULL,
	[nome] [varchar](255) NOT NULL
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[TipoCondicao]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TipoCondicao](
	[idTipoCondicao] [int] NOT NULL,
	[nome] [varchar](100) NOT NULL,
	[descricao] [text] NULL,
 CONSTRAINT [PK_TIPOCONDICAO] PRIMARY KEY CLUSTERED 
(
	[idTipoCondicao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Vilao]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Vilao](
	[idVilao] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](50) NOT NULL,
	[descricao] [varchar](255) NULL,
	[ataque] [int] NOT NULL,
	[defesa] [int] NOT NULL,
	[idEspecie] [int] NOT NULL,
 CONSTRAINT [PK_VILAO] PRIMARY KEY CLUSTERED 
(
	[idVilao] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Vilao_Capitulo]    Script Date: 6/18/2016 9:28:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vilao_Capitulo](
	[idVilao] [int] NOT NULL,
	[idCapitulo] [int] NOT NULL
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Capitulo] ADD  CONSTRAINT [DF__Capitulo__startC__15502E78]  DEFAULT ('0') FOR [startChapter]
GO
ALTER TABLE [dbo].[Login] ADD  CONSTRAINT [DF__Login__nivel__1DE57479]  DEFAULT ('U') FOR [nivel]
GO
ALTER TABLE [dbo].[Atributo_Historia]  WITH CHECK ADD  CONSTRAINT [Atributo_Historia_fk0] FOREIGN KEY([idHistoria])
REFERENCES [dbo].[Historia] ([idHistoria])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Atributo_Historia] CHECK CONSTRAINT [Atributo_Historia_fk0]
GO
ALTER TABLE [dbo].[Atributo_Historia]  WITH CHECK ADD  CONSTRAINT [Atributo_Historia_fk1] FOREIGN KEY([idAtributo])
REFERENCES [dbo].[Atributo] ([idAtributo])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Atributo_Historia] CHECK CONSTRAINT [Atributo_Historia_fk1]
GO
ALTER TABLE [dbo].[Atributo_Personagem]  WITH CHECK ADD  CONSTRAINT [Atributo_Personagem_fk0] FOREIGN KEY([idPersonagem])
REFERENCES [dbo].[Personagem] ([idPersonagem])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Atributo_Personagem] CHECK CONSTRAINT [Atributo_Personagem_fk0]
GO
ALTER TABLE [dbo].[Atributo_Personagem]  WITH CHECK ADD  CONSTRAINT [Atributo_Personagem_fk1] FOREIGN KEY([idAtributo])
REFERENCES [dbo].[Atributo] ([idAtributo])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Atributo_Personagem] CHECK CONSTRAINT [Atributo_Personagem_fk1]
GO
ALTER TABLE [dbo].[Caminho]  WITH CHECK ADD  CONSTRAINT [Caminho_fk0] FOREIGN KEY([idHistoriaOrigem])
REFERENCES [dbo].[Capitulo] ([idCapitulo])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Caminho] CHECK CONSTRAINT [Caminho_fk0]
GO
ALTER TABLE [dbo].[Caminho]  WITH CHECK ADD  CONSTRAINT [Caminho_fk1] FOREIGN KEY([idHistoriaDestino])
REFERENCES [dbo].[Capitulo] ([idCapitulo])
GO
ALTER TABLE [dbo].[Caminho] CHECK CONSTRAINT [Caminho_fk1]
GO
ALTER TABLE [dbo].[Caminho]  WITH CHECK ADD  CONSTRAINT [Caminho_fk2] FOREIGN KEY([idCondicao])
REFERENCES [dbo].[Condicao] ([idCondicao])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Caminho] CHECK CONSTRAINT [Caminho_fk2]
GO
ALTER TABLE [dbo].[Capitulo]  WITH CHECK ADD  CONSTRAINT [Capitulo_fk0] FOREIGN KEY([idHistoria])
REFERENCES [dbo].[Historia] ([idHistoria])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Capitulo] CHECK CONSTRAINT [Capitulo_fk0]
GO
ALTER TABLE [dbo].[Condicao]  WITH CHECK ADD  CONSTRAINT [Condicao_fk0] FOREIGN KEY([idTipoCondicao])
REFERENCES [dbo].[TipoCondicao] ([idTipoCondicao])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Condicao] CHECK CONSTRAINT [Condicao_fk0]
GO
ALTER TABLE [dbo].[Historia]  WITH CHECK ADD  CONSTRAINT [Historia_fk0] FOREIGN KEY([idCriador])
REFERENCES [dbo].[Login] ([idLogin])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Historia] CHECK CONSTRAINT [Historia_fk0]
GO
ALTER TABLE [dbo].[Item]  WITH CHECK ADD  CONSTRAINT [Item_fk0] FOREIGN KEY([idEspecie])
REFERENCES [dbo].[Especie] ([idEspecie])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Item] CHECK CONSTRAINT [Item_fk0]
GO
ALTER TABLE [dbo].[Item_Capitulo]  WITH CHECK ADD  CONSTRAINT [Item_Capitulo_fk0] FOREIGN KEY([idCapitulo])
REFERENCES [dbo].[Capitulo] ([idCapitulo])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Item_Capitulo] CHECK CONSTRAINT [Item_Capitulo_fk0]
GO
ALTER TABLE [dbo].[Item_Capitulo]  WITH CHECK ADD  CONSTRAINT [Item_Capitulo_fk1] FOREIGN KEY([idItem])
REFERENCES [dbo].[Item] ([idItem])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Item_Capitulo] CHECK CONSTRAINT [Item_Capitulo_fk1]
GO
ALTER TABLE [dbo].[Item_Personagem]  WITH CHECK ADD  CONSTRAINT [Item_Personagem_fk0] FOREIGN KEY([idItem])
REFERENCES [dbo].[Item] ([idItem])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Item_Personagem] CHECK CONSTRAINT [Item_Personagem_fk0]
GO
ALTER TABLE [dbo].[Item_Personagem]  WITH CHECK ADD  CONSTRAINT [Item_Personagem_fk1] FOREIGN KEY([idPersonagem])
REFERENCES [dbo].[Personagem] ([idPersonagem])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Item_Personagem] CHECK CONSTRAINT [Item_Personagem_fk1]
GO
ALTER TABLE [dbo].[Login_Personagem]  WITH CHECK ADD  CONSTRAINT [Login_Personagem_fk0] FOREIGN KEY([idLogin])
REFERENCES [dbo].[Login] ([idLogin])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Login_Personagem] CHECK CONSTRAINT [Login_Personagem_fk0]
GO
ALTER TABLE [dbo].[Login_Personagem]  WITH CHECK ADD  CONSTRAINT [Login_Personagem_fk1] FOREIGN KEY([idPersonagem])
REFERENCES [dbo].[Personagem] ([idPersonagem])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Login_Personagem] CHECK CONSTRAINT [Login_Personagem_fk1]
GO
ALTER TABLE [dbo].[Vilao]  WITH CHECK ADD  CONSTRAINT [Vilao_fk0] FOREIGN KEY([idEspecie])
REFERENCES [dbo].[Especie] ([idEspecie])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Vilao] CHECK CONSTRAINT [Vilao_fk0]
GO
ALTER TABLE [dbo].[Vilao_Capitulo]  WITH CHECK ADD  CONSTRAINT [Vilao_Capitulo_fk0] FOREIGN KEY([idVilao])
REFERENCES [dbo].[Vilao] ([idVilao])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Vilao_Capitulo] CHECK CONSTRAINT [Vilao_Capitulo_fk0]
GO
ALTER TABLE [dbo].[Vilao_Capitulo]  WITH CHECK ADD  CONSTRAINT [Vilao_Capitulo_fk1] FOREIGN KEY([idCapitulo])
REFERENCES [dbo].[Capitulo] ([idCapitulo])
ON UPDATE NO ACTION
ON DELETE NO ACTION
GO
ALTER TABLE [dbo].[Vilao_Capitulo] CHECK CONSTRAINT [Vilao_Capitulo_fk1]
GO
USE [master]
GO
ALTER DATABASE [RPGSystem] SET  READ_WRITE 
GO
